#!/bin/sh


# carry out port redirection from localhost toward the registry within cluster
CMD="apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000"
docker run -d --network=host --restart unless-stopped alpine ash -c "$CMD"
