apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-srv
    project: innovative-extension
  name: mongodb-srv
  namespace: sagan
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-dpl
    project: innovative-extension
  namespace: sagan
  name: mongodb-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        project: innovative-extension
    spec:
      containers:
      - image: mongo:6
        name: mongodb
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
