apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-srv
    project: innovative-extension
  name: mongodb-srv
  namespace: sagan
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: sagan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Minikube's default dynamic provisioning storage class

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-dpl
    project: innovative-extension
  namespace: sagan
  name: mongodb-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        project: innovative-extension
    spec:
      containers:
      - image: mongo:6
        name: mongodb
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
